### ISSUE TITLE
Error compiling for board adafruit feather m0

### ISSUE THREAD

**Issue by Constance-Balaam** [adafruit/Adafruit-Feather-M0-Bluefruit-LE-PCB#1]
Hello I have been following this project. https://makezine.com/projects/led-matrix-handbag/
I am up to step 17 where I am having issues, I have downloaded the libraries it says necessary and made sure arduino is using the correct port and board. However, when uploading the BlueFruitConfig.h code : https://github.com/geekmomprojects/woven-led-handbag/blob/master/led_matrix_handbag/BluefruitConfig.h 
I get this error and cannot figure out why.

Arduino: 1.8.16 (Mac OS X), Board: "Adafruit Feather M0, Small (-Os) (standard), Arduino, Off"

/Users/conniebalaam/Library/Arduino15/packages/adafruit/tools/arm-none-eabi-gcc/9-2019q4/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: ../arduino_cache_81498/core/core_2f08c6f201c5d2959d88e155028a29c2.a(main.cpp.o): in function `main':
/Users/conniebalaam/Library/Arduino15/packages/adafruit/hardware/samd/1.7.5/cores/arduino/main.cpp:50: undefined reference to `setup'
/Users/conniebalaam/Library/Arduino15/packages/adafruit/tools/arm-none-eabi-gcc/9-2019q4/bin/../lib/gcc/arm-none-eabi/9.2.1/../../../../arm-none-eabi/bin/ld: /Users/conniebalaam/Library/Arduino15/packages/adafruit/hardware/samd/1.7.5/cores/arduino/main.cpp:54: undefined reference to `loop'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Adafruit Feather M0.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

any advice would be appreciated thank you, I am a student and very new to this :)

**Comment by ladyada** [comment]
hi yes you need to post in arduino or adafruit forums to learn how to compile code :)
